export const Countries = [
  { label: 'Afghanistan', value: 'AFGHANISTAN' },
  { label: 'Angola', value: 'ANGOLA' },
  { label: 'Australia', value: 'AUSTRALIA' },
  { label: 'Austria', value: 'AUSTRIA' },
  { label: 'Azerbaijan', value: 'AZERBAIJAN' },
  { label: 'Bangladesh', value: 'BANGLADESH' },
  { label: 'Belgium', value: 'BELGIUM' },
  { label: 'Bolivia', value: 'BOLIVIA' },
  { label: 'Brazil', value: 'BRAZIL' },
  { label: 'Cambodia', value: 'CAMBODIA' },
  { label: 'Canada', value: 'CANADA' },
  { label: 'Chile', value: 'CHILE' },
  { label: 'China', value: 'CHINA' },
  { label: 'Costa Rica', value: 'COSTA_RICA' },
  { label: 'Côte d’Ivoire', value: 'COTE_DIVOIRE' },
  { label: 'Croatia', value: 'CROATIA' },
  { label: 'Czech Republic', value: 'CZECH_REPUBLIC' },
  { label: 'Denmark', value: 'DENMARK' },
  { label: 'Dominican Republic', value: 'DOMINICAN_REPUBLIC' },
  { label: 'Egypt', value: 'EGYPT' },
  { label: 'Ethiopia', value: 'ETHIOPIA' },
  { label: 'Finland', value: 'FINLAND' },
  { label: 'France', value: 'FRANCE' },
  { label: 'Gabon', value: 'GABON' },
  { label: 'Georgia', value: 'GEORGIA' },
  { label: 'Germany', value: 'GERMANY' },
  { label: 'Ghana', value: 'GHANA' },
  { label: 'Guatemala', value: 'GUATEMALA' },
  { label: 'Honduras', value: 'HONDURAS' },
  { label: 'Hungary', value: 'HUNGARY' },
  { label: 'India', value: 'INDIA' },
  { label: 'Indonesia', value: 'INDONESIA' },
  { label: 'Israel', value: 'ISRAEL' },
  { label: 'Italy', value: 'ITALY' },
  { label: 'Japan', value: 'JAPAN' },
  { label: 'Kazakhstan', value: 'KAZAKHSTAN' },
  { label: 'Kyrgyzstan', value: 'KYRGYZSTAN' },
  { label: 'Laos', value: 'LAOS' },
  { label: 'Latvia', value: 'LATVIA' },
  { label: 'Malaysia', value: 'MALAYSIA' },
  { label: 'Mexico', value: 'MEXICO' },
  { label: 'Moldova', value: 'MOLDOVA' },
  { label: 'Mongolia', value: 'MONGOLIA' },
  { label: 'Nepal', value: 'NEPAL' },
  { label: 'Netherlands', value: 'NETHERLANDS' },
  { label: 'New Zealand', value: 'NEW_ZEALAND' },
  { label: 'Pakistan', value: 'PAKISTAN' },
  { label: 'Panama', value: 'PANAMA' },
  { label: 'Paraguay', value: 'PARAGUAY' },
  { label: 'Peru', value: 'PERU' },
  { label: 'Philippines', value: 'PHILIPPINES' },
  { label: 'Poland', value: 'POLAND' },
  { label: 'Portugal', value: 'PORTUGAL' },
  { label: 'Romania', value: 'ROMANIA' },
  { label: 'Rwanda', value: 'RWANDA' },
  { label: 'Senegal', value: 'SENEGAL' },
  { label: 'Singapore', value: 'SINGAPORE' },
  { label: 'Slovenia', value: 'SLOVENIA' },
  { label: 'South Africa', value: 'SOUTH_AFRICA' },
  { label: 'South Korea', value: 'SOUTH_KOREA' },
  { label: 'Spain', value: 'SPAIN' },
  { label: 'Sri Lanka', value: 'SRI_LANKA' },
  { label: 'Switzerland', value: 'SWITZERLAND' },
  { label: 'Taiwan', value: 'TAIWAN' },
  { label: 'Tanzania', value: 'TANZANIA' },
  { label: 'Thailand', value: 'THAILAND' },
  { label: 'Turkey', value: 'TURKEY' },
  { label: 'Ukraine', value: 'UKRAINE' },
  { label: 'United Arab Emirates', value: 'UNITED_ARAB_EMIRATES' },
  { label: 'United Kingdom', value: 'UNITED_KINGDOM' },
  { label: 'United States', value: 'UNITED_STATES' },
  { label: 'Uzbekistan', value: 'UZBEKISTAN' },
  { label: 'Venezuela', value: 'VENEZUELA' },
  { label: 'Vietnam', value: 'VIETNAM' },
  { label: 'Zambia', value: 'ZAMBIA' },
];
